### ISSUE TITLE
No data.

### ISSUE THREAD

**Issue by poleguy** [rdiaz82/mqttSqlLite#2]
I've tried out your logger. Pretty neat. I'm using it to log temperature. I've hit a case where it returns OK but no data for a log/query/days or log/query/minutes query but correctly returns data for log/query/last.

My only clue is that there is no data in the last few hours, and I'm asking for 7 days worth. Any idea how it could return 'OK' but no data? 

I'm starting to debug, but no luck yet.

The code seems to set 'OK' all over the place, so it's not clear how the logic to determine 'OK' even works. Maybe it would have been better to set 'OK' in one place at the start and then set 'KO' on any error detection?

**Comment by rdiaz82** [comment]
Hi!! Nice to see that you like the project and you are using it!! Are you setting the `option` parameter in the request for the query days/hours/minutes. Here in the text you can see how is the format: https://github.com/rdiaz82/mqttSqlLite/blob/079e0abc32930aa28c13ece8e66d831ea896943d/tests/test_logs.py#L22

**Comment by poleguy** [comment]
Yes. It works fine if there is recent data in the database. It works on and off for a few days and then it stops working when there is no fresh data in the database. e.g. in the case when the temperature monitor goes off line for a few hours and isn't adding new data. I'll update here when I have boiled it down to a minimal broken test case. I think it may be a timeout of some sort, but what is bad is that it is returning OK with no data, which indicates a design problem of some sort, as that's not a valid response to a well formed log/query/days query. 

It should either succeed with the correct data and OK, or fail with KO, right?

**Comment by rdiaz82** [comment]
The return of OK indicates that the database has been sucessfully queried and it returns doesn't return any result. "No results" doesn't mean a KO

**Comment by rdiaz82** [comment]
If something is failing with the database query here is a possible clue to check:
https://github.com/rdiaz82/mqttSqlLite/blob/079e0abc32930aa28c13ece8e66d831ea896943d/mqttsqlite/core/logs_controller.py#L21
Here is where the database is queried, I need to check if this method returns any kind of exception that can be intercepted at higher level.

**Comment by poleguy** [comment]
I found the issue. It was not a bug in paho.mqtt.client or in mqttsqlite per-se, but my abuse of the callback functions, use of a global variable, and multiple message streams. 

I blame my mistake on trying to hack the query topic example from the readme into workable code.
This is not exactly what I did, but is a modification of the readme example to iindicate where I went wrong:
```
import paho.mqtt.client as mqtt
import json
import mqttsqlite.settings.private_settings as Settings

QUERY_PASSWORD = 'YOUR PASSWORD'
MQTT_HOST = 'YOUR HOST'
MQTT_PORT = 'YOUR PORT'
ROOT_TOPIC = 'YOUR ROOT LOGGER TOPIC by default logger/'
desired_topic = 'desired/new/topic'

payload = {}
# specify a unique name for this client to identify our messages in on_message
payload['client'] = 'simple_example'
payload['topic'] = desired_topic
payload['options'] = 20
payload['options'] = 2000
payload['password'] = QUERY_PASSWORD

# global variable to hold result
output_data = None
# global variable to hold result... this is a very bad idea:
# received_data = None

def on_connect(client, userdata, flags, rc):
    client_topic = ROOT_TOPIC + COMMAND
    client.subscribe(ROOT_TOPIC + 'response') #important to subscribe to response topic before request to the logger
    client.publish(client_topic, json.dumps(payload))


def on_message(client, userdata, msg):
    global output_data
    # uncomment to see why it's dangerous to put any real code here:
    # this error will cause a silent failure and lock-up as it isn't printed to the console
    # output_data['cause error']
    received_data = json.loads(msg.payload)
    # check if the message is from a client
    if 'client' in received_data:
        # process data if the message is from this client
        if received_data['client'] == payload['client']:
            print('Received Message for client %s from Logger' % payload['client'])
            # save the data to be processed outside of this callback function
            output_data = received_data
            client.disconnect()

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

client.connect(MQTT_HOST, MQTT_PORT, 60)

client.loop_forever()

# print the data
print('Received Data:')
print(output_data)
```

This code above works. My code had used received_data as a global variable, and it was being overwritten by a subsequent message that wasn't even to my client. This caused intermittent failures depending on timing of multiple clients.

I blame the example in a small degree, because it showed no practical example of how to get the data out of the on_message function and back out to the 'rest of the program'. You can't actually write and debug code effectively within on_message because it prevents any error messages from being reported. (Why? not sure: is there an evil 'try' catching all errors in there somewhere? Is it due to multiprocessing or threading?)  So I wanted to process (in this example: just print) the message after the loop was done. The quick and dirty way to do this was a global variable, but that's not a good solution the way I did it by making received_data a global directly.  As written it works, but really the example should have a queue or other proper mechanism to get the data out.

It's not obvious that it's not safe to make received_data global variable, issue the client.disconnect()  and expect the last received_data to be correct. Additional on_message events can (and do) come after the client.disconnect is issued and it can clobber the global received_data contents before you saw what you consider should be the 'last one'.

Lesson learned. Please consider updating the readme using my above example, or better, a full non-blocking example with a queue mechanism. At least fix the two spelling errors in your example. :-)
